source/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include(('django.contrib.auth.urls', 'accounts'), namespace='accounts')),
    path('', include('webapp.urls', namespace='webapp'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from .views import ArticleListView, ArticleDetailView, ArticleCreateView, ArticleUpdateView, \
    UserDetailView, AuthorListView, AuthorDetailView, AuthorCreateView, AuthorUpdateView, \
    soft_delete_author, BookListView, BookCreateView, BookDetailView, BookUpdateView, BookDeleteView, \
    CommentCreateView

app_name = 'webapp'

urlpatterns = [
    path('', BookListView.as_view(), name='book_list'),
    path('books/create/', BookCreateView.as_view(), name='book_create'),
    path('books/<int:pk>/', BookDetailView.as_view(), name='book_detail'),
    path('books/<int:pk>/comment', CommentCreateView.as_view(), name='comment_create'),
    path('books/<int:pk>/edit', BookUpdateView.as_view(), name='book_update'),
    path('books/<int:pk>/delete', BookDeleteView.as_view(), name='book_delete'),
    path('articles/', ArticleListView.as_view(), name='article_list'),
    path('articles/<int:pk>/', ArticleDetailView.as_view(), name='article_detail'),
    path('articles/create/', ArticleCreateView.as_view(), name='article_create'),
    path('articles/<int:pk>/edit/', ArticleUpdateView.as_view(), name='article_update'),
    path('user/<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('authors/', AuthorListView.as_view(), name='author_list'),
    path('authors/<int:pk>/', AuthorDetailView.as_view(), name='author_detail'),
    path('authors/create/', AuthorCreateView.as_view(), name='author_create'),
    path('authors/<int:pk>/edit', AuthorUpdateView.as_view(), name='author_update'),
    path('authors/<int:pk>/delete', soft_delete_author, name='author_delete')
]

source/webapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class SoftDeleteManager(models.Manager):
    def active(self):
        return self.filter(is_deleted=False)

    def deleted(self):
        return self.filter(is_deleted=True)


class Author(models.Model):
    full_name = models.CharField(max_length=200, verbose_name="Автор")
    birth_date = models.DateField(null=True, blank=True, verbose_name="Дата рождения")
    death_date = models.DateField(null=True, blank=True, verbose_name="Дата смерти")
    biography = models.TextField(max_length=5000, null=True, blank=True, verbose_name="Биография автора")
    photo = models.ImageField(upload_to='author_images', blank=True, null=True, verbose_name="Фотография")
    is_deleted = models.BooleanField(default=False)

    objects = SoftDeleteManager()

    def __str__(self):
        return self.full_name

    def get_absolute_url(self):
        return reverse('webapp:author_detail', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = "Автор"
        verbose_name_plural = "Авторы"


class Book(models.Model):
    title = models.CharField(max_length=200, verbose_name="Название")
    author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name='author')
    publish_year = models.CharField(max_length=200, verbose_name="Год издания")
    file = models.FileField(upload_to='book_file', blank=True, null=True, verbose_name="Файл")
    cover = models.ImageField(upload_to='book_cover', blank=True, null=True, verbose_name="Обложка")
    description = models.TextField(max_length=3000, null=True, blank=True, verbose_name="Описание")

    def get_absolute_url(self):
        return reverse('webapp:author_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Книга"
        verbose_name_plural = "Книги"


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='book')
    text = models.TextField(max_length=2000, verbose_name="Текст")
    created_at = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('webapp:author_detail', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Коментарии"


class Article(models.Model):
    title = models.CharField(max_length=200, verbose_name="Заголовок")
    text = models.TextField(max_length=5000, null=True, blank=True, verbose_name="Текст статьи")
    author = models.ForeignKey(User, blank=True, verbose_name="Автор", on_delete=models.CASCADE)
    image = models.ImageField(upload_to='article_images', blank=True, null=True, verbose_name="Картинка")
    created_at = models.DateTimeField(auto_now=True, verbose_name="Дата и время создания")

    def __str__(self):
        return f"{self.pk}. {self.title} | {self.author.username}"

    def get_absolute_url(self):
        return reverse('webapp:article_detail', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = "Статья"
        verbose_name_plural = "Статьи"

source/webapp/forms.py
from django import forms
from .models import Article, Author, Book, Comment


class ArticleForm(forms.ModelForm):
    def clean(self):
        if not self.cleaned_data['text'] and not self.cleaned_data['image']:
            raise forms.ValidationError('Хотя бы одно из полей "Текст" и "Картинка" должно быть заполнено.')
        return super().clean()

    class Meta:
        model = Article
        fields = ['title', 'text', 'image']


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['full_name', 'death_date', 'birth_date', 'biography', 'photo']


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'author', 'publish_year', 'file', 'cover', 'description']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

source/webapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, UpdateView, View
from webapp.forms import ArticleForm, AuthorForm, BookForm, CommentForm
from webapp.models import Article, Author, Book, Comment
from django.urls import reverse


class ArticleListView(ListView):
    template_name = 'article_list.html'
    model = Article
    ordering = ['-created_at']


class AuthorListView(ListView):
    template_name = 'author_list.html'
    model = Author

    def get_queryset(self):
        return Author.objects.filter(is_deleted=False)


class BookListView(ListView):
    template_name = 'book_list.html'
    model = Book


class ArticleDetailView(DetailView):
    template_name = 'article_detail.html'
    model = Article


class UserDetailView(DetailView):
    template_name = 'user_detail.html'
    model = User


class AuthorDetailView(DetailView):
    template_name = 'author_detail.html'
    model = Author

    # def get_context_data(self, **kwargs):
    #     context = super(AuthorDetailView, self).get_context_data(**kwargs)
    #     context['book_list'] = Book.objects.all().order_by('author_id')
    #     return context


class BookDetailView(DetailView):
    template_name = 'book_detail.html'
    model = Book


class CommentCreateView(LoginRequiredMixin, CreateView):
    template_name = 'book_detail.html'
    form_class = CommentForm
    model = Comment

    def get_context_data(self, **kwargs):
        pass

    def get_queryset(self):
        return Comment.objects.filter('-created_at')


class ArticleCreateView(LoginRequiredMixin, CreateView):
    template_name = 'article_create.html'
    form_class = ArticleForm
    model = Article

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class AuthorCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    template_name = 'author_create.html'
    form_class = AuthorForm
    model = Author
    permission_required = 'administrations'


class BookCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    template_name = 'book_create.html'
    form_class = BookForm
    model = Book
    permission_required = 'administrations'

    def get_success_url(self):
        return reverse('webapp:book_detail', kwargs={'pk': self.object.pk})


class ArticleUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    template_name = 'article_update.html'
    form_class = ArticleForm
    model = Article

    def get_permission_required(self):
        return None

    def has_permission(self):
        return self.request.user == self.get_object().author


class AuthorUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    template_name = 'author_update.html'
    form_class = AuthorForm
    model = Author
    permission_required = 'administrations'


class BookUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    template_name = 'book_update.html'
    form_class = BookForm
    model = Book
    permission_required = 'administrations'

    def get_success_url(self):
        return reverse('webapp:book_detail', kwargs={'pk': self.object.pk})


def soft_delete_author(request, pk):
    if request.user.is_superuser:
        author = get_object_or_404(Author, pk=pk)
        author.is_deleted = True
        author.save()
        return redirect('webapp:author_list')
    else:
        raise PermissionDenied


class BookDeleteView(LoginRequiredMixin, PermissionRequiredMixin, View):
    template_name = 'book_detail.html'
    model = Book
    permission_required = 'administrations'

    def get(self, request, pk):
        book = get_object_or_404(Book, pk=pk)
        book.delete()
        return redirect('webapp:book_list')

source/webapp/templates/article_create.html
{% extends 'base.html' %}

{% block title %}Новая статья{% endblock %}

{% block content %}
    <h1 class="mt-3">Добавить статью</h1>
    <form method="post" enctype="multipart/form-data" action="{% url 'webapp:article_create' %}">
        {% csrf_token %}
        {% include 'partial/article_form.html' %}
    </form>
{% endblock %}

source/webapp/templates/article_detail.html
{% extends 'base.html' %}

{% block title %}Статья{% endblock %}

{% block content %}
    <h1 class="mt-2">{{ article.title }}</h1>
    {% if user == article.author %}
        <a class="float-right" href="{% url 'webapp:article_update' article.pk %}">Редактировать</a>
    {% endif %}
    <p class="card-text">{{ article.author }} | {{ article.created_at }}</p>
    {% if article.image %}
        <div class="img-wrapper">
            <img class="card-img" src="{{ article.image.url }}" alt="{{ article.image.name }}">
        </div>
    {% endif %}
    <p class="mt-3">{{ article.text }}</p>
{% endblock %}

source/webapp/templates/article_list.html
{% extends 'base.html' %}

{% block title %}Статьи{% endblock %}

{% block content %}
    {% for article in article_list %}
        <div class="card mb-3 mt-2" style="max-width: 540px;">
            <div class="row no-gutters">
                <div class="col-md-4">
                    {% if article.image %}
                        <div class="img-wrapper">
                            <img src="{{ article.image.url }}" class="card-img" alt="{{ article.image.name }}">
                        </div>
                    {% endif %}
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h2 class="card-title">
                            <a href="{% url 'webapp:article_detail' article.pk %}" class="card-link">{{ article.title }}</a>
                        </h2>
                        <p class="card-text">{{ article.text }}</p>
                        <p class="card-text">
                            <small class="text-muted">{{ article.author }} | {{ article.created_at }}</small>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}

{% endblock %}

source/webapp/templates/article_update.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}Изменить статью{% endblock %}

{% block content %}
    <h1 class="mt-3">Изменить статью</h1>
    <form method="post" enctype="multipart/form-data" action="{% url 'webapp:article_update' object.pk %}">
        {% csrf_token %}
        {% include 'partial/article_form.html' %}
    </form>
{% endblock %}

source/webapp/templates/author_create.html
{% extends 'base.html' %}

{% block title %}Новый автор{% endblock %}

{% block content %}
    <h1 class="mt-3">Добавить автора</h1>
    <form method="post" enctype="multipart/form-data" action="{% url 'webapp:author_create' %}">
        {% csrf_token %}
        {% include 'partial/author_form.html' %}
    </form>
{% endblock %}

source/webapp/templates/author_detail.html
{% extends 'base.html' %}

{% block title %}Автор{% endblock %}

{% block content %}
    {% if user.is_superuser %}
        <a href="{% url 'webapp:author_update' author.pk%}" class="btn btn-success mt-2">Редактировать</a>
        <a href="{% url 'webapp:author_delete' author.pk%}" class="btn btn-danger mt-2">Удалить</a>
    {% endif %}
    <div class="row">
        <div class="card-body col-sm-8">
            <h1 class="text-center">Биография</h1>
            <p class="text">{{ author.biography }}</p>
        </div>
        <div class="col-sm-4 mt-2" style="width: 18rem;">
        <div class="card-title text-center"><h2>{{ author.full_name }}</h2>
            {% if author.photo %}
                <img src="{{ author.photo.url }}" class="card-img-top" alt="{{ author.photo.name }}">
            {% endif %}
        </div>
        </div>
    </div>
     <h2 class="card-title">Книги данного автора:</h2>
    {% for book in author.author.all %}
        <div class="list-group mt-2">
        <a href="{% url 'webapp:book_detail' book.pk %}" class="list-group-item list-group-item-action">
            <div class="d-flex w-100 justify-content-between">
                <h4 class="mb-1">{{ book.title }}</h4>
                {% if book.publish_year %}:
                    <small class="text-muted">Год выхода: {{ book.publish_year }}</small>
                {% endif %}
            </div>
            <small class="text-muted">{{ book.description }}</small>
        </a>
    </div>
    {% endfor %}

{% endblock %}

source/webapp/templates/author_list.html
{% extends 'base.html' %}

{% block title %}Авторы{% endblock %}

{% block content %}
    <div class="row">

        {% for author in author_list %}
            <div class="card m-2 col-sm-3">
                {% if author.photo %}
                    <img src="{{ author.photo.url }}" class="img-thumbnail" alt="{{ author.photo.name }}">
                {% endif %}
                <div class="card-body">
                    <a class="link" href="{% url 'webapp:author_detail' author.pk %}">{{ author.full_name }}</a>
                </div>
            </div>
        {% endfor %}

    </div>
{% endblock %}

source/webapp/templates/author_update.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}Редактирование{% endblock %}

{% block content %}
    <h1 class="mt-3">Редактировать статью автора</h1>
    <form method="post" enctype="multipart/form-data" action="{% url 'webapp:author_update' object.pk %}">
        {% csrf_token %}
        {% include 'partial/author_form.html' %}
    </form>
{% endblock %}

source/webapp/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% block styles %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
    <div class="container">

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="{% url 'webapp:book_list' %}" class="nav-link">Главная</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'webapp:author_list' %}" class="nav-link">Авторы</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'webapp:article_create' %}" class="nav-link">Добавить статью</a>
                </li>
                {% if user.is_superuser %}
                    <li class="nav-item">
                        <a href="{% url 'webapp:author_create' %}" class="nav-link">Добавить автора</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'webapp:book_create' %}" class="nav-link">Добавить книгу</a>
                    </li>
                {% endif %}

                {% block menu %}{% endblock %}
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{% url 'webapp:user_detail' user.pk %}" class="nav-link">личный кабинет: {{ user.username }}</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'accounts:logout' %}" class="nav-link">выйти</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a href="{% url 'accounts:login' %}" class="nav-link">Вход</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>

    </nav>
<div class="container">
    {% block content %}{% endblock %}
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
{% block scripts %}{% endblock %}
</body>
</html>

source/webapp/templates/book_create.html
{% extends 'base.html' %}

{% block title %}Новая книга{% endblock %}

{% block content %}
    <h1 class="mt-3">Добавить книгу</h1>
    <form method="post" enctype="multipart/form-data" action="{% url 'webapp:book_create' %}">
        {% csrf_token %}
        {% include 'partial/book_form.html' %}
    </form>
{% endblock %}

source/webapp/templates/book_detail.html
{% extends 'base.html' %}

{% block title %}Книга{% endblock %}

{% block content %}
    {% if user.is_superuser %}
        <a href="{% url 'webapp:book_update' book.pk %}" class="btn btn-success mt-2">Редактировать</a>
        <button type="button" class="btn btn-danger mt-2" data-toggle="modal" data-target="#exampleModal{{ book.pk }}">
            Удалить
        </button>
    {% endif %}

    {% if book.file %}
        <a href='{{ MEDIA_URL }}' download="{{ book.file }}" class="btn btn-primary mt-2">Скачать</a>
    {% endif %}
    <div class="modal fade" id="exampleModal{{ book.pk }}" tabindex="-1" role="dialog"
         aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Подтверждение удаления книги</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Вы уверены, что хотите удалить {{ book.title }}?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                    <a href="{% url 'webapp:book_delete' book.pk %}" class="btn btn-danger">Удалить</a>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="card-body col-sm-8">
            <h1 class="card-title">{{ book.title }}</h1>
            <p class="card-text">{{ book.description }}</p>

        </div>

        <div class="col-sm-4 mt-2" style="width: 18rem;">
            {% if book.cover %}
                <img src="{{ book.cover.url }}" class="img-thumbnail" alt="{{ book.cover.name }}">
            {% else %}
                <img src="/media/no-image.png" class="img-thumbnail" alt="Заглушка">
            {% endif %}
        </div>
    </div>

    <h2 class="mt-3">Добавить комментарий</h2>
    <form method="post" enctype="multipart/form-data" action="{% url 'webapp:comment_create' book.pk %}">
        {% csrf_token %}
        {% include 'partial/comment_form.html' %}
    </form>

    {% for comment in book.book.all %}
        <ul class="list-group col-sm-8 mt-2">
            <li class="list-group-item text-center">{{ comment.user }} |
                <small>{{ comment.created_at }}</small>
            </li>
            <li class="list-group-item ">{{ comment.text }}
                {% if comment.user.pk == request.user.pk %}
                    <a class="float-right" href="#">удалить</a>
                    <a class="float-right" href="#">редактировать/</a>
                {% endif %}
            </li>
        </ul>
    {% endfor %}



{% endblock %}

source/webapp/templates/book_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Авторы{% endblock %}

{% block content %}
    <div class="row">
    {% for book in book_list %}
        <div class="card m-2" style="max-width: 540px;">
            <div class="row no-gutters">
                {% if book.cover %}
                    <div class="col-md-6">
                        <img src="{{ book.cover.url }}" class="card-img-top" alt="{{ book.cover.name }}">
                    </div>
                {% else %}
                    <div class="col-md-6">
                        <img src="/media/no-image.png" class="card-img" alt="Заглушка">
                    </div>
                {% endif %}
                <div class="col-md-6">
                    <div class="card-body">
                        <h5 class="card-title">
                            <a href="{% url 'webapp:book_detail' book.pk %}" class="nav-link">{{ book.title }}</a>
                        </h5>
                        <p class="card-text">
                            <small class="text-muted">{{ book.publish_year }}</small>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
{% endblock %}

source/webapp/templates/book_update.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}Редактирование{% endblock %}

{% block content %}
    <h1 class="mt-3">Редактировать книгу</h1>
    <form method="post" enctype="multipart/form-data" action="{% url 'webapp:book_update' book.pk %}">
        {% csrf_token %}
        {% include 'partial/book_form.html' %}
    </form>
{% endblock %}

source/webapp/templates/user_detail.html
{% extends 'base.html' %}

{% block title %}Пользователь{% endblock %}

{% block content %}
    <table class="table table-bordered mt-3" style="max-width: 540px;">
        <thead>
        <tr>
            <td scope="col">Имя пользователя</td>
            <th scope="col">{{ user.username }}</th>
        </tr>
        <tr>
            <td scope="col">Почта</td>
            <th scope="col">{{ user.email }}</th>
        </tr>
        </thead>
    </table>
{% endblock %}